---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: daylight-components
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: fluxCapacitor
  url: https://gitlab.com/surfliner/surfliner/
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/daylight/frontend/flux
