---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: daylight-components
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: fluxCapacitor
  url: https://gitlab.com/surfliner/surfliner/
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/daylight/frontend/flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: daylight-components
  namespace: flux-system
spec:
  interval: 10m
# targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: daylight-components
  path: "./daylight/frontend/flux"
  prune: true
  timeout: 1m
---
apiVersion: v1
kind: Namespace
metadata:
  name: daylightcomponents-review