---
apiVersion: v1
kind: Namespace
metadata:
  name: daylightcomponents-review
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: repo-dlc-review
  namespace: daylightcomponents-review
spec:
  interval: 1m0s
  ref:
    branch: fluxCapacitor
  url: https://gitlab.com/surfliner/surfliner/
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/daylight/frontend/flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustomize-dlc-review
  namespace: daylightcomponents-review
spec:
  interval: 10m
  targetNamespace: daylightcomponents-review
  sourceRef:
    kind: GitRepository
    name: repo-dlc-review
  path: "./daylight/frontend/flux"
  prune: true
  timeout: 1m

