apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: nginxtest
resources:
  - ../base/nginx
  - namespace.yaml
patches:
  - path: nginx-values.yaml
    target:
      kind: HelmRelease
